### ISSUE TITLE
Enable multiple sensors for same siteID

### ISSUE THREAD

**Issue by fredrikbaberg** [fredrikbaberg/ha-sensor-sl#2]
For a site, enable splitting into multiple sensors.

**Comment by fredrikbaberg** [comment]
To reduce number of API-calls, the idea is to for each siteid specify which line(s) and direction(s) should be included.
configuration-wise it would be something like this:
```
sensor:
  - platform: sl
    ri4key: <key>
    siteid: <siteid>
    departures:
        - name: <name>
          lines: <lines>
          direction: <direction>
          sensor: <sensor>
```
